apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsu-deployment
  labels:
    app: devsu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsu
  template:
    metadata:
      labels:
        app: devsu
    spec:
      containers:
        - name: devsu
          image: ghcr.io/alex-flores-dev/demo:latest
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8000"